mattn/efm-langserver

go.mod
go.sum
langserver/handler.go

I wanted to instal this package with `go get`.
However, the following error occured:
```
$ go get github.com/mattn/efm-langserver
go: finding github.com/sourcegraph/jsonrpc2 latest
go: finding github.com/haya14busa/errorformat latest
go: github.com/mattn/efm-langserver imports
github.com/mattn/efm-langserver/langserver imports
github.com/haya14busa/errorformat: github.com/haya14busa/errorformat@v0.0.0-20190922193611-a885a245ae0b: parsing go.mod:
module declares its path as: github.com/reviewdog/errorformat
but was required as: github.com/haya14busa/errorformat
```
It seems that `github.com/haya14busa/errorformat` has moved to `github.com/reviewdog/errorformat`.
I fixed that and add `go.mod` `go.sum`.

Fix import path and support go modules

---

langserver/handler.go

With efm-langserver config:
```yaml
languages:
json:
format-command: 'jq .'
```
```json
{
"a":
"b",
"c":
"d"
}
```
is formated to
```json
{
"a": "b",
"c": "d"
}
}
```

Format range should be based on input text

---

langserver/handler.go

eslint for example need filename to know which parser to use

Allow using ${INPUT} placeholder for filename when lint-stdin = true

---

README.md

Thanks for this plugin.
I added it `to REAME.md`.
Only the example of `json` using `prettier` was added with "comments out".

Add "prettier formatter" for html, css and json to example config

---

README.md

Add `lint-formats` due to duplicate results from `:LspDocumentDiagnostics`

Add lint-formats settings for flake8 and mypy in README

---

README.md

Add the following tools to the example YAML config in the project README:
- ShellCheck: shell script linter
- shfmt: shell script formatter
- Pandoc: markdown and reStructuredText formatter
- restructuredtext-lint: reStructuredText linter
- hadolint: dockerfile linter

Doc: add more tools

---

langserver/handle_text_document_completion.go
langserver/handle_text_document_formatting.go
langserver/handle_text_document_hover.go
langserver/handle_text_document_symbol.go
langserver/handler.go

strings.Contains is the preferred way to check for the presence of a
substring. See https://staticcheck.io/docs/checks#S1003

Fix: replace strings.Index with strings.Contains

---

README.md

Prevent unsaved changes from being reverted on write by reading from
stdin instead of from disk.

Fix: format shfmt on stdin

---

langserver/handle_text_document_did_close.go
langserver/handle_text_document_did_open.go

The return values of `h.openFile` and `h.closeFile` in
`handleTextDocumentDidOpen` and `handleTextDocumentDidClose` were
previously unchecked. This commit causes their errors to be returned if
they exist.

Fix: check missed return values

---

README.md

Thanks for this language server.
Added [Psalm](https://github.com/vimeo/psalm) linter for php to `REAME.md`.

Add "psalm" for php to example config in README

---

langserver/config.go
langserver/handle_initialize.go
langserver/handler.go

In my current setup, I'd like to disable the tags-based definition provider. Because the language-specific server (for example, `pyls`) handles definition requests, the results from `efm-langserver` create duplicates, and then `vim-lsp` prompts me to select which of two equivalent locations to jump to.
I don't know if this is the best way to implement the behavior toggle. I've added a top level config setting called `provide-definition`. If that is turned off, then on initialization `DefinitionProvider` is turned off. For backwards compatibility, the setting defaults to enabled.
Let me know what you think, and thank you for creating this useful tool.

Make it possible to disable "go to definition" support

---

langserver/handle_text_document_did_change.go
langserver/handle_text_document_did_open.go
langserver/handle_text_document_did_save.go
langserver/handler.go
langserver/lsp.go

I implemented PublishDiagnosticsParams.version.
ref:
- https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics
- https://github.com/microsoft/language-server-protocol/issues/201
This convenient for lsp client to handle diagnostics by multiple servers on the same language.
<details>
<summary>Example response</summary>
```go
type TestParams struct {
a
}
```
gopls and golint respond the following against the above code.
Both responses include the same version.
```json
{
"uri": "file:///home/notomo/workspace/efm-langserver/langserver/lsp.go",
"diagnostics": [
{
"range": {
"end": {
"character": 2,
"line": 185
},
"start": {
"character": 1,
"line": 185
}
},
"source": "compiler",
"message": "undeclared name: a",
"severity": 1
}
],
"version": 50
}
{ …
```

Add Version to PublishDiagnosticsParams

---

README.md

Add "lua-format" formatter to README
Binary download is recommended for easy installation of `lua-format`.
- Binary download
- https://github.com/Koihik/vscode-lua-format/tree/master/bin
- GitHub
- https://github.com/Koihik/LuaFormatter
- LuaRocks
- https://luarocks.org/modules/tammela/luaformatter

Add "lua-format" formatter to README

---

README.md

Laravel (PHP Web Framework) has a template file called `blade`.
Add blade-formatter to README.
- GitHub
- https://github.com/shufo/blade-formatter
- npm
- https://www.npmjs.com/package/blade-formatter
- **vim-blade**: blade syntax and filetype plugin
- https://github.com/jwalton512/vim-blade

Add blade-formatter to README

---

schema.json

When if schema lost `commands comamand os` vocabulary. This  PR is adding.
If it does not match, it will be closing.

doc: schema: add command os description and type define

---

langserver/handle_text_document_formatting.go

Some formatter like `black` print information to stderr (`All done! ✨ 🍰 ✨ 1 file reformatted.`)
This adds an option to ignore stderr output and only use stdout

Add FormatIgnoreStderr option

---

langserver/diff.go
langserver/handle_text_document_formatting.go

This diffs the output of formatter against the current buffer, to only update relevant parts.
For Vim, this keeps jumps, marks and folds in the buffer in places that are not changed.
This is copied (and slightly modified) from the golang lsp
https://github.com/golang/tools/blob/78b158585360beccadc3faac6e35759f491831f3/internal/lsp/diff/myers/diff.go

Adds copy of myers diff algorithm

---

langserver/handler.go

According to https://vim-jp.org/vimdoc-en/quickfix.html#error-file-format, the lowest severity is note, not hint, which the code seems to check for.
I stumbled on this when migrating from diagnostic-languageserver, and saw that my shellcheck hints turned to errors.

Fix lowest severity character

---

README.md
langserver/handle_text_document_formatting.go
langserver/lsp.go

With this PR `format-command` can specify placeholder that get filled in by `FormattingOptions` passed in from the client.
LSP spec: https://microsoft.github.io/language-server-protocol/specification.html#textDocument_formatting
The syntax looks like `${--cmd-line-flag:optionName}`
If the option is not supplied from the client, the placeholder will be removed.
Options support string, int and boolean values.
String and int values will resolve to `--cmd-line-flag value`.
Boolean values will resolve to `--cmd-line-flag`
Client then can call formatting with options like `{ "tabWidth": 4, "singleQute": true }`

Add support for FormattingOptions

---

README.md
main.go

When running the server with Neovim, Neovim's log fills up slowly with stderr output from efm-langserver, mostly the examples below:
```
2020/11/18 08:17:55 efm-langserver: reading on stdin, writing on stdout
2020/11/18 08:37:27 jsonrpc2 handler: notification "exit" handling error: jsonrpc2: code -32601 message: method not supported: exit
```
This adds a command line flag `-q` that disables those stderr logs. The logging to file built in to efm-langserver is not affected by the quiet flag.

Quiet flags

---

README.md

From an issue/discussion here: https://github.com/mattn/efm-langserver/issues/62#issuecomment-729707136

Updates README with working `mix credo` linter usage example for elixir

---

README.md
langserver/config.go
langserver/handle_initialize.go
langserver/handle_text_document_code_action.go
langserver/handle_text_document_formatting.go
langserver/handle_workspace_did_change_configuration.go
langserver/handler.go
langserver/lsp.go
main.go

This allows the client to change the configuration on the fly.
As well as replace the need for a config file.
Clients send a `DidChangeConfiguration` notification to update the
configuration. Only supplied values will be overwritten.
Supported values are:
1. `Languages`
2. `RootMarkers`
3. `Commands`
4. `LogLevel`
5. `LintDebounce`
In addition, because the capabilities are now dynamic, The client can
specify the server capabilities on initialization with
`InitializeParams`.
Supported values are:
1. `Completion`
2. `Hover`
3. `CodeAction`
4. `DocumentSymbol`
5. `DocumentFormatting`
config file can still be used as before. `DidChangeConfiguration` only overwrites provided properties.
LSP spec:
https://microsoft.github.io/language-server-protocol/specification.html#workspace_didChangeConfigur …

Add support for DidChangeConfiguration

---

schema.json

- support hover-type enum (select `markdown` or `plaintext`)
- support env string array (validate `any=any`)

feat: Update schema

---

README.md
langserver/handler.go

The idea is to allow clients to identify which linter is sending the
diagnostic.

Add optional lint-source

---

schema.json

set minimum 1 (include)
----
log level max defined?
If do so, fix together.
And other repair point remain?
(I think, stdin default value...)

small fix - schema log-level

---

langserver/handler.go
langserver/handler_test.go

I ran into an issue while running eslint on a rather large file using eslint via efm-langserver. My setup sends diagnostics requests to the langserver whenever a change is done, and eslint takes around 4s for the largish file. With the current release of efm-langserver, this means that diagnostics requests are backed up, and requests are processed in sequence, allowing the linter to finish before processing the next request. This means that for example 3 lint requests would take 12 seconds and any diagnostics requests coming in during that time would add another 4 seconds to that.
This change spawns each linter in its own goroutine, and using `context.Context` a running request for a specific URI is canceled if a new request for linting arrives.
Hopefully my description makes sense!

Prevent multiple linters running for the same URI

---

README.md

- **black**
- https://github.com/psf/black
- https://black.readthedocs.io/en/stable/ 
- **autopep8**
- https://github.com/hhatto/autopep8
- **yapf**
- https://github.com/google/yapf
- **isort**
- https://github.com/PyCQA/isort
- https://pycqa.github.io/isort/
(Use `black` + `isort`)

Add various python formatters to REAMDE

---

README.md

It's a very small fix, but I think the whitelist wasn't recommended anymore, so I fixed it.

fix whitelist to allowlist in the vim-lsp config

---

schema.json

When using the current `schema.json` with `yaml-language-server`, completion and hover does not work properly in "tools" entries.
Lint is working fine.
I've adjusted the completion and hover to work as well.
**.vimrc(vim-lsp-settings)**
```vim
let g:lsp_settings = {
\ 'yaml-language-server': {
\   'workspace_config': {
\     'yaml': {
\       'schemas': {
\         'https://raw.githubusercontent.com/mattn/efm-langserver/master/schema.json': ['/efm-langserver/config.yaml'],
\       },
\     },
\   },
\ }
\}
```
**.vimrc(vim-lsp-settings)**
> Set the schema.json of the branch of the pull request
```vim
let g:lsp_settings = {
\ 'yaml-language-server': {
\   'workspace_config': {
\     'yaml': {
\       'schemas': {
\         'https://raw.githubusercontent.com/yaegassy/efm-langserver/fix-schem …
```

fix "tools" entry in schema.json

---

README.md

Using the unix format doesn't provide an easy way to break up the message and differentiate between errors and warnings. Changing the format to that of visualstudio gives us a message we can parse a bit better to highlight errors and warnings differently.

docs(eslint): improve formatting in eslint example configuration

---

langserver/handle_shutdown.go

Prevents a panic from happening when shutdown happens when there is no `lintTimer` defined.
Such a situation can happen if there is no lintCommand set for a given language.
Addresses the `panic` problem brought up in https://github.com/mattn/efm-langserver/issues/110#issuecomment-816541527
I've verified that the `panic` no longer happens after editing a Markdown file (for which I have only a `formatCommand` defined, without any `lintCommand`) - the process exists cleanly (verified in `~/.cache/nvim/lsp.log`)
<details>
<summary>Logs from before&after</summary>
Before:
```
[ ERROR ] 2021-04-18T12:51:37+0200 ] ...nt_nvimEd5bbH/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]  "rpc"   "efm-langserver"        "stderr"        "2021/04/18 12:51:37 lint for LanguageID not supported: markdown\n"
[ …
```

Stop the lint timer only if it is set

---

langserver/handle_text_document_code_action.go
langserver/handle_text_document_completion.go
langserver/handle_text_document_formatting.go
langserver/handle_text_document_symbol.go
langserver/handler.go

Some linters or formatters need the current project/workspace root to run correctly (e.g. Python isort needs it to know which modules should be considered 'local'). 
EFM already knows the calculated workspace but so far we are not exposing it. This PR adds it as a new variable `${ROOT}` to become available in the `format-command` or `lint-command`.

Support adding LSP workspace root to command

---

langserver/handler.go

don't use intermediate config variable in configs loop as the source pointer, as it will always point to the last config in the list.

bugfix: source-pointer

---

langserver/handler.go

Some formatters support multiple file format but requires file extension hint (eg: `deno fmt`).
Adding `FILEEXT` var might help with those kind of formatter.

Adding file ext var

---

langserver/handler.go

The checking condition is incorrect which causes panic. The following is my stack trace.
```txt
panic: runtime error: index out of range [27] with length 27
goroutine 34 [running]:
github.com/mattn/efm-langserver/langserver.(*File).WordAt(0xc00009ba40, 0x1b, 0x11, 0x0, 0x1)
github.com/mattn/efm-langserver/langserver/handler.go:129 +0x2f5
github.com/mattn/efm-langserver/langserver.(*langHandler).lint(0xc0000f8000, 0x11ede98, 0xc00018a000, 0xc0000d2140, 0x41, 0x0, 0x0, 0x0, 0x0, 0x105f960)
github.com/mattn/efm-langserver/langserver/handler.go:452 +0xf39
github.com/mattn/efm-langserver/langserver.(*langHandler).linter.func1(0xc0000f8000, 0x11ede98, 0xc00018a000, 0xc0000d2140, 0x41)
github.com/mattn/efm-langserver/langserver/handler.go:234 +0x74
created by …
```

bugfix: index out-of-bound cases panic

---

README.md
langserver/handler.go
langserver/handler_test.go

This should address the comments to previous pr #95 from @sentriz.
I also added an example configuration for pylint use with efm in the readme.

add example pylint configuration to readme, fix error in pr #95, tests

---

langserver/duration.go
langserver/handle_text_document_code_action.go
langserver/handle_text_document_formatting.go
langserver/handle_workspace_did_change_configuration.go
langserver/handler.go
main.go

The PR
1) Trying to improve the lintDebounce setup.  Currently it only accepts int and it likely to mistake the time unit to ms. The golang Duration unit is ns.  That means the setup need to use 500000000 to debounce 500ms. I did a quick grep of setups (dotfiles) in github. Most people are setting this field to 500, I believe they mean to set up debounce to 500ms. The changes allow user setup the debounce to "500ms" or "0.5s".
2) Add format debounce. I saw random failures when multiple format tools were configured and will trigger lsp format multiple times. This sometime result in an incorrect result.

Add format debounce and improve debounce time setup

---

README.md

First of all, thank you so much for building this, I am enjoying it with my neovim :)
I was having a hard time while setting up eruby linting and formatting with neovim. The linting part was fine, but the problem was with the formatting. After searching through the issues, I have found someone with a similar [issue](https://github.com/mattn/efm-langserver/issues/84).
In the end, I manage to get it to work by taking the solution from this [comment](https://github.com/mattn/efm-langserver/issues/24#issuecomment-590889562) in a closed issue.
Therefore, I am doing this PR to update the eruby config in the README.md so that it will be easier for others to setup eruby linting and formatting.

Update eruby config to include format-stdin=true

---

langserver/handle_text_document_completion.go
langserver/handle_text_document_formatting.go
langserver/handle_text_document_hover.go
langserver/handler.go
langserver/handler_go112.go
langserver/handler_go113.go
langserver/lsp.go
main.go

- used strings.ReplaceAll(...) instead of strings.Replace(..., -1);
- added what seems to be missing types (constants with logically related names, but different types, i.e. LogError, LogWarning);
- other, minor cleanup.

Minor cleanup, simplifications:

---

langserver/handler.go

When file path contains non-existed folder, `ioutil.ReadDir` returns non-nil `err`, and the loop become infinite loop because `dir`, `prev` did not get updated.
When `err != nil`, `files = []` so we don't need to specially handle this error.

Fix infinite loop in matchRootPath

---

langserver/handle_initialize.go

I was experiencing the issue reported here: https://github.com/mattn/efm-langserver/issues/157
This only seems to happen for me in the my home directory, and after investigating a bit, it seems that the root cause is that coc is sending the parameter `rootUri` as null in its first message. Here's the abbreviated message I captured:
```
"params": {
"processId": 356405,
"rootPath": null,
"rootUri": null,
"capabilities": {
```
According to [this](https://microsoft.github.io/language-server-protocol/specification#initialize), this behavior should be supported by the LSP server, so I added a check for parsing this field.
The error happens in [this line](https://github.com/mattn/efm-langserver/blob/41a7cc3736a6208b699ef4a1371cf56acf8dac28/langserver/handler.go#L180) and the error message comes …

fix `Error: parse "": empty url` when rootUri is null

---

README.md

Hey. Thanks for the great language server.
I noticed when https://github.com/mattn/efm-langserver/pull/179 got merged that it included a number of spelling mistakes.
Since people (including me) often blindly copy and paste from README's, I thought I'd help prevent issues and fix them for you.

Fix spelling mistakes & formatting tidy up

---

langserver/handler.go
langserver/handler_test.go

Resolves #143
Thank you for creating this great software. I would like to use `efm-langserver` with my linter to check all the files in a workspace, and need a feature described below.
- An option to support workspace wide diagnostics
- ignore command line arguments in a cross-platform way
- publish diagnostics for other files than a submitted document
- appropriately erase diagnostics which no longer exist 🌟
To implement 🌟, we need to have a state for last published document URIs, because language servers should publish empty diagnostics to erase previous diagnostics as specified in LSP.
I define the state as `lastPublishedURIs`, and added `LintWorkspace` option for this feature.
I would appreciate it if you would review it.

Support workspace level linters

---

langserver/handler.go
langserver/handler_test.go

The idea is that we still want to publish an empty list of diagnostics
if the document being processed doesn't have any errors.
Fixes #197.

langserver/handler: initialize diagnostics map with the current file

---

langserver/handle_text_document_code_action.go

Removed a second append of the arg when exec code action at not Windows.

Removed a second append of the arg

---

langserver/handle_text_document_code_action.go
langserver/handle_text_document_completion.go
langserver/handle_text_document_formatting.go
langserver/handle_text_document_hover.go
langserver/handle_text_document_symbol.go
langserver/handler.go

Adjusted to log at `INFO` level on format success - my neovim logs are getting a little noisy. I also went ahead and made similar changes for the other handlers.
I'm also wondering if you're interested in me writing up a change to use enums for the log levels? Something like:
```go
type LogLevel int
const (
ERROR LogLevel = iota + 1
WARN
INFO
DEBUG
TRACE
)
```
Thanks for all your hard work!

feat: adjust log levels

---

langserver/handle_text_document_formatting.go
langserver/handle_text_document_formatting_test.go

Support skipping textDocument/formatting with requireMarker too

---

langserver/handler.go
langserver/handler_test.go

If `%l` is empty, the `Lnum` will be `0` and diagnostic location will be on line `-1`.
This makes diagnostics invisible in some clients such as Visual Studio Code.

Fix cases without line number

---

langserver/handle_initialize.go
langserver/handle_text_document_code_action.go
langserver/handle_workspace_did_change_configuration.go
langserver/handler.go
schema.json

- `*` is not a wildcard in `TriggerCharacters`
- Currently only literal `*` triggers completion
- Add `trigger-chars` as setting
- Set `.` by default

Support setting trigger-chars and set . by default

---

README.md
main.go

Hi, just installed this program and so far it works great, but I noticed that when launched it creates `~/.config` folder which I moved away on my system. This patch fixes this.

Add support for XDG_CONFIG_HOME

---

.gitattributes
.github/workflows/ci.yml
.golangci.yaml
Makefile
langserver/diff.go
langserver/handle_initialize.go
langserver/handle_shutdown.go
langserver/handle_text_document_code_action.go
langserver/handle_text_document_completion.go
langserver/handle_text_document_definition.go
langserver/handle_text_document_did_change.go
langserver/handle_text_document_did_close.go
langserver/handle_text_document_did_open.go
langserver/handle_text_document_did_save.go
langserver/handle_text_document_formatting.go
langserver/handle_text_document_hover.go
langserver/handle_text_document_symbol.go
langserver/handle_workspace_did_change_configuration.go
langserver/handle_workspace_did_change_workspace_folders.go
langserver/handle_workspace_execute_command.go
langserver/handle_workspace_workspace_folders.go
langserver/handler.go
langserver/handler_test.go
main.go

`golangci-lint` is a Go linters aggregator: https://golangci-lint.run/
`golint` is currently unmantained, `revive` attempts to be a replacement
for it.
For now we only enable very basic linters + `revive`, more linters will be
added in the future.

Replace `golint` with `golangci-lint`

---

langserver/handle_initialize.go
langserver/lsp.go

When https://github.com/tsuyoshicho/vim-efm-langserver-settings is used, `config.yaml` is provided.
However, if you want to disable some features, it is useful to be able to override the capability with `initializationOptions`.

Override capability when initialization options are set.

---

langserver/handle_text_document_formatting.go
langserver/handler.go

This pull request fixes a data race in text document formatting from the master 34b8f5bf9c80a361c56245131fa23b197f94b293
```
$ go test  ./... -race
?   	github.com/mattn/efm-langserver	[no test files]
[]
==================
WARNING: DATA RACE
Write at 0x00c0001823e0 by goroutine 10:
github.com/mattn/efm-langserver/langserver.(*langHandler).formatRequest.func1()
/Users/khant/temp/efm-langserver/langserver/handle_text_document_formatting.go:41 +0x3e
Previous write at 0x00c0001823e0 by goroutine 8:
github.com/mattn/efm-langserver/langserver.(*langHandler).formatRequest()
/Users/khant/temp/efm-langserver/langserver/handle_text_document_formatting.go:40 +0x1cd
github.com/mattn/efm-langserver/langserver.TestFormattingRequireRootMatcher() …
```

Fix data race in text document formatting

---

README.md

[Eglot](https://github.com/joaotavora/eglot) is stands for Emacs Polyglot, not Elgot.

Fix typo (Eglot)

---

langserver/handler.go

close #274 
Fixed escaping of brackets in paths when replacing `${INPUT}` `${FILENAME}` `${ROOT}`.

fix: unescaped brackets in path
