mattn/efm-langserver

- README.md
- cmd/efm-langserver/main.go
- langserver/handle_initialize.go
- langserver/handle_shutdown.go
- langserver/handle_text_document_did_change.go
- langserver/handle_text_document_did_close.go
- langserver/handle_text_document_did_open.go
- langserver/handle_text_document_did_save.go
- langserver/handler.go
- langserver/lsp.go
flag arguments will be removed to support new LSP commands.
> [Drastic change] Load configuration yaml file

- README.md
Thanks for this plugin.
I added it to `REAME.md`.
> Add phpstan to example for config.yaml

- README.md
Thanks for this plugin.
I added it to `REAME.md`.
> Add "flake8" and "mypy" for python to example config

- README.md
Add lint-formats due to duplicate results from `:LspDocumentDiagnostics`
> Add lint-formats settings for "vint" in README

- langserver/handler.go
Errorformat parser is currently processing line by line.
`errorformat.Scanner` support multiline lint messages.
> Support multiline errorformat with errorformat.Scanner

- langserver/handle_text_document_formatting.go
Instead of using the first specified format command, apply all of format commands in sequence.
> Allow using multiple formatter

- README.md
So small, but I was confused on it.
> Fix `log` to `logfile` in the example for config

- langserver/handler.go
- schema.json
> Add lint-debounce

- langserver/handler.go
This pull-request will fix loading `lint-debounce` from config.
> Fix lint-debounce

- README.md
> Add homebrew installation

- langserver/handle_shutdown.go
> Stop the timer before closing channel

- langserver/handler.go
> Add lint severity setting

- langserver/duration.go
- main.go
Fix https://github.com/mattn/efm-langserver/pull/141
> Fix duration

- langserver/handler.go
- schema.json
for https://github.com/mattn/efm-langserver/issues/145
> Support Prefix

- langserver/handle_text_document_completion.go
- langserver/handle_text_document_formatting.go
- langserver/handle_text_document_hover.go
- langserver/handler.go
Debian buster still use Go1.11
Ref #150
> Use strings.Replace

- schema.json
- updated category map to correct value
> Minor schema updates

- langserver/config.go
- langserver/handle_text_document_hover.go
- langserver/handler.go
> Add hover-chars

- langserver/handle_text_document_hover.go
- langserver/handler_test.go
- Added test cases and fix for handling of hover-chars
- If these changes are not desirable, please teach me :bow:
Also, if this PR is mergeable, please release new version with these changes?
> Fix and test handling of hover-chars

- Makefile
> Makefile: use go install instead of go get

- README.md
This will make maintaining this list a lot easier.
> Sort tools' config alphabetically

- README.md
- langserver/handle_text_document_formatting.go
- langserver/handle_text_document_formatting_test.go
- langserver/handler.go
- langserver/lsp.go
- langserver/util.go
> feat: textDocument/rangeFormatting

- langserver/handle_initialize.go
- langserver/handler.go
- langserver/lsp.go
> fix: announce `rangeFormattingProvider` `ServerCapabilities`

- langserver/handle_text_document_did_change.go
- langserver/handle_text_document_did_open.go
- langserver/handle_text_document_did_save.go
- langserver/handler.go
- langserver/handler_test.go
> Add an option to run some linters only on save

- langserver/handle_initialize.go
> fix: restore serverCapabilities inference

- README.md
Add guide configuration for SublimeText LSP
> Add guide configuration for SublimeText LSP
